stages:
 - build
 - test
 - quality

.build_image_debian_docker: &build_image_debian_docker_definition
  tags:
   - docker
   - linux
  before_script:
   - ./tools/ci/setup_buildenv_debian.sh

.runtime_image_debian_docker: &runtime_image_debian_docker_definition
  tags:
   - docker
   - linux
  before_script:
   - ./tools/ci/setup_runtime_debian.sh

.image_lrz_haswell: &image_lrz_haswell_definition
  tags:
   - linux
   - ssh
   - lrzhaswell

.build_template_make: &build_definition_make
  stage: build
  script:
   - mkdir -p build
   - cd build
   - cmake $CMAKE_FLAGS
       -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_PREFIX_PATH=$PREFIX ..
   - cmake --build .
   - cmake --build . --target install
  artifacts:
    paths:
     - "build/"

.test_template_cpp_examples: &test_definition_cpp_examples
  stage: test
  script:
   - cd build
   - mbsolve-tool/mbsolve-tool -d ziolkowski1995 -e 100e-15
       -m cpu-fdtd-red-2lvl-cvr-rodr -w hdf5
   - mbsolve-tool/mbsolve-tool -d song2005 -e 16e-15
       -m cpu-fdtd-red-3lvl-cvr-rodr -w hdf5
   - mbsolve-tool/mbsolve-tool -d marskar2011 -e 40e-15
       -m cpu-fdtd-red-6lvl-cvr-rodr -w hdf5
  artifacts:
    paths:
     - "build/"

.test_template_python_examples: &test_definition_python_examples
  stage: test
  script:
   - cd build
   - PYTHONPATH=.:$PYTHONPATH python3 ../tools/python/ziolkowski1995.py
   - PYTHONPATH=.:$PYTHONPATH python3 ../tools/python/song2005.py
  artifacts:
    paths:
     - "build/"

build-debian-8:
  only:
   - master
  image: debian:8
  <<: *build_image_debian_docker_definition
  <<: *build_definition_make

test-cpp-examples-debian-8:
  only:
   - master
  image: debian:8
  <<: *runtime_image_debian_docker_definition
  dependencies:
   - build-debian-8
  <<: *test_definition_cpp_examples

test-py-examples-debian-8:
  only:
   - master
  image: debian:8
  <<: *runtime_image_debian_docker_definition
  dependencies:
   - build-debian-8
  <<: *test_definition_python_examples

build-debian-9:
  only:
   - master
  image: debian:9
  <<: *build_image_debian_docker_definition
  <<: *build_definition_make

test-cpp-examples-debian-9:
  only:
   - master
  image: debian:9
  <<: *runtime_image_debian_docker_definition
  dependencies:
   - build-debian-9
  <<: *test_definition_cpp_examples

test-py-examples-debian-9:
  only:
   - master
  image: debian:9
  <<: *runtime_image_debian_docker_definition
  dependencies:
   - build-debian-9
  <<: *test_definition_python_examples

build-debian-10:
  image: debian:10
  <<: *build_image_debian_docker_definition
  <<: *build_definition_make

test-cpp-examples-debian-10:
  image: debian:10
  <<: *runtime_image_debian_docker_definition
  dependencies:
   - build-debian-10
  <<: *test_definition_cpp_examples

test-py-examples-debian-10:
  image: debian:10
  <<: *runtime_image_debian_docker_definition
  dependencies:
   - build-debian-10
  <<: *test_definition_python_examples

format-cpp:
  image: debian:10
  <<: *build_image_debian_docker_definition
  stage: quality
  dependencies:
   - build-debian-10
  script:
   - mkdir -p build
   - cd build
   - cmake ..
   - make format
   - cd ..
   - git diff > build/format_check_revisionlist.txt
   - if [ `git diff | wc -l` -gt "0" ]; then false; fi
  artifacts:
    when: on_failure
    paths:
     - "build/format_check_revisionlist.txt"
  allow_failure: true

build-clang:
  variables:
    CMAKE_FLAGS: "-DCMAKE_C_COMPILER=clang-7 -DCMAKE_CXX_COMPILER=clang++-7"
  image: debian:10
  <<: *build_image_debian_docker_definition
  <<: *build_definition_make

test-cpp-examples-clang:
  image: debian:10
  <<: *runtime_image_debian_docker_definition
  dependencies:
   - build-clang
  <<: *test_definition_cpp_examples

test-py-examples-clang:
  image: debian:10
  <<: *runtime_image_debian_docker_definition
  dependencies:
   - build-clang
  <<: *test_definition_python_examples

build-intel:
  variables:
    CMAKE_FLAGS: "-DCMAKE_C_COMPILER=icc -DCMAKE_CXX_COMPILER=icpc"
  <<: *image_lrz_haswell_definition
  <<: *build_definition_make

test-cpp-examples-intel:
  <<: *image_lrz_haswell_definition
  dependencies:
   - build-intel
  <<: *test_definition_cpp_examples

test-python-examples-intel:
  <<: *image_lrz_haswell_definition
  dependencies:
   - build-intel
  <<: *test_definition_python_examples
